### ISSUE TITLE
Allow endpoint configuration through the Cachet API

### ISSUE THREAD

**Issue by xel1045** [mtakaki/cachet-url-monitor#10]
With the Cachet API, we can retrieve the list of configured components at `/api/v1/components`, then perform a basic health check for all components with an URL through GET.

**Comment by mtakaki** [comment]
That's an interesting proposal, but what if not every URL accepts a GET request? Or is the idea to fetch all component URLs in the beginning? It would still be missing the HTTP method, expected status code, body content, etc, to properly verify the URLs.

**Comment by xel1045** [comment]
Maybe by targeting the components with a regex? For example:

````
endpoint:
  match_components:
    url: "^https?://www.google.com/.*$" # optional
    title: ".*" # optional
    group_id: 1 # optional
    # [...]
  method: GET
  timeout: 0.010 # seconds
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: ".*<body>.*"
````

Then, for the status code, it would be nice to accept ranges like 200-299 for all successful statuses.
