### ISSUE TITLE
Error al actualizar un incidente

### ISSUE THREAD

**Issue by steel2k2** [mtakaki/cachet-url-monitor#108]
Me sale el error siguiente:
  WARNING [2020-07-19 20:15:46,620] cachet_url_monitor.configuration.Configuration.Gorm,io - Incident update failed with status [404], message: ""
     INFO [2020-07-19 20:15:46,620] cachet_url_monitor.configuration.Configuration.Gorm,io - No changes to component status.
  WARNING [2020-07-19 20:15:50,193] cachet_url_monitor.configuration.Configuration.Gorm,io - Incident update failed with status [404], message: ""
     INFO [2020-07-19 20:15:50,193] cachet_url_monitor.configuration.Configuration.Gorm,io - No changes to component status.
  WARNING [2020-07-19 20:15:53,855] cachet_url_monitor.configuration.Configuration.Gorm,io - Incident update failed with status [404], message: ""
     INFO [2020-07-19 20:15:53,855] cachet_url_monitor.configuration.Configuration.Gorm,io - No changes to component status.
==================================================================================
La configuracion del yaml es la siguiente:
  - name: Gorm,io
    url: https://testurl
    method: GET
    header:
      SOME-HEADER: SOME-VALUE
    timeout: 2 # seconds
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
      - type: LATENCY
        threshold: 2
      - type: REGEX
        regex: ".*<body>.*"
    allowed_fails: 0
    component_id: 1
    metric_id: 1
    action:
      - CREATE_INCIDENT
      - UPDATE_STATUS
    public_incidents: true
    latency_unit: ms
    frequency: 2
cachet:
  api_url: http://cachetserver/api/v1
  token:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_TOKEN
    - type: TOKEN
      value: Hl5ibgnXVuGPB42NPwQ0

**Comment by mtakaki** [comment]
Es que puedes escribir tu configuracion en un code block? Creo que el problema es en tu `component_id`, quizas tienes un otro id?
Also, can we switch to English for the sake of keeping it helpful for other folks?

**Comment by steel2k2** [comment]
mtakaki, este es el archivo de configuración

`endpoints:
  - name: swagger
    url: https://prairial.run.goorm.io/
    method: GET
    header:
      SOME-HEADER: SOME-VALUE
    timeout: 2.01
    expectation:
      - type: HTTP_STATUS
        status_range: 200-300
        incident: MAJOR
      - type: LATENCY
        threshold: 4
      - type: REGEX
        regex: '.*(<body).*'
    allowed_fails: 1
    frequency: 3
    component_id: 1
    metric_id: 1
    action:
      - CREATE_INCIDENT
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
cachet:
  api_url: http://192.168.0.20/api/v1
  token:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_TOKEN
    - type: TOKEN
      value: Hl5ibgnXVuGPB4sNPwQ0
`

**Comment by steel2k2** [comment]
Este es el archivo de configuración

**Comment by steel2k2** [comment]
mtakaki, esta es la configuración
```
endpoints:
  - name: swagger
    url: https://prairial.run.goorm.io/
    method: GET
    header:
      SOME-HEADER: SOME-VALUE
    timeout: 2.01
    expectation:
      - type: HTTP_STATUS
        status_range: 200-300
        incident: MAJOR
      - type: LATENCY
        threshold: 4
      - type: REGEX
        regex: '.*(<body).*'
    allowed_fails: 1
    frequency: 3
    component_id: 1
    metric_id: 1
    action:
      - CREATE_INCIDENT
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
cachet:
  api_url: http://192.168.0.20/api/v1
  token:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_TOKEN
    - type: TOKEN
      value: Hl5ibgnXVuGPB4sNPwQ0
```
