### ISSUE TITLE
Url unreachable issue 

### ISSUE THREAD

**Issue by Project-neuron** [mtakaki/cachet-url-monitor#110]
Hello 

I am running into an issue with the system stating that the url is unreachable 

``` yml 
endpoints:
  - name: Google
    url: google
    method: GET
    timeout: 10
    expectation:
      - type: HTTP_STATUS
        status_range: 200-300
    allowed_fails: 0
    frequency: 30
    component_id: 1
    action:
      - CREATE_INCIDENT
      - UPDATE_STATUS
    public_incidents: true
    latency_unit: ms
cachet:
  api_url: http://<url>/api/v1
  token:
    - type: TOKEN
      value: "my_token" 
```  
  INFO [2020-10-02 20:56:06,814] cachet_url_monitor.configuration.Configuration.Apps at Ithaca - Component current status: ComponentStatus.OPERATIONAL
     INFO [2020-10-02 20:56:06,814] cachet_url_monitor.configuration.Configuration.Apps at Ithaca - Monitoring URL: GET https://www.google.com/
     INFO [2020-10-02 20:56:06,814] cachet_url_monitor.configuration.Configuration.Apps at Ithaca - Registered expectation: 'HTTP status range: [200, 300['
     INFO [2020-10-02 20:56:06,814] cachet_url_monitor.configuration.Configuration.Apps at Ithaca - Registered expectation: 'Latency threshold: 10.0000 seconds'
     INFO [2020-10-02 20:56:06,815] cachet_url_monitor.scheduler - Registering action CREATE_INCIDENT
     INFO [2020-10-02 20:56:06,815] cachet_url_monitor.scheduler - Registering action UPDATE_STATUS
     INFO [2020-10-02 20:56:06,815] cachet_url_monitor.scheduler.Scheduler - Starting monitor agent...
  WARNING [2020-10-02 20:56:11,821] cachet_url_monitor.configuration.Configuration.Apps at Ithaca - The URL is unreachable: GET https://www.google.com/
   
```  

curls that I run work fine from the box I have the containers in. So I am not sure what I am missing. 

Any assistance would be appreciated. I looked over the last time this issue was brought up and tried the suggestions there but to no avail. 

Best
