### ISSUE TITLE
config.yml file seg fault when passing value rapped in " "

### ISSUE THREAD

**Issue by gamkiller77** [mtakaki/cachet-url-monitor#17]
I am using your contianer image in a Kubernetes / OpenShift 3.3 deployment.  I gotten to work really well and wanted to rap it up as a PaaS offering.  One item that is odd about k8s is that you can not just mount a config file but use configmap.  This worked great and was able to get your container to work.

I then figured i make this in to a template.  I setup the template but in the parameter section boolean and numbers base values have to ramped in " " or it fails validation.  Well when these params are passed to the container as a configmap all the values are still ramped in " " and your app seg faults.  Was not sure if there was a way to say " " rapped value is still valid.

**Comment by mtakaki** [comment]
I'm sorry but I'm not quite following what's happening. I just tested it locally, having a value wrapped into double quotes (`"`), and it worked fine. So my configuration looks like this:

```yaml
endpoint:
  url: http://localhost:8080/swagger
  method: GET
  timeout: 0.01
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: '.*(<body).*'
cachet:
  api_url: https://demo.cachethq.io/api/v1
  token: my_token
  component_id: 1
  create_incident: "true"
frequency: 30
```

You can see that `create_incident` has `"true"` and it works with no problem. Could you please share the stack trace or the error you're exactly getting?
