### ISSUE TITLE
API URL fails when send a email 

### ISSUE THREAD

**Issue by nasatome** [mtakaki/cachet-url-monitor#45]
with the following docker-compose (I'm behind a reverse proxy: traefik)

```
version: "3"

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgress
    networks:
      - cachethq_internal
    restart: always

  cachet:
    image: cachethq/docker:2.3-latest
    networks:
      - ak_cachethq_outside
      - ak_cachethq_internal
#    environment:
#...
    depends_on:
      - postgres
    restart: always
  cachet_url_monitor:
    image: mtakaki/cachet-url-monitor
    networks:
      - ak_cachethq_internal
    depends_on:
      - cachet
    volumes:
      - ${PWD}/.config.yml:/usr/src/app/config/config.yml:ro
    restart: always

networks:
  cachethq_outside:
    external:
      name: traefik_proxy
  cachethq_internal:
    driver: bridge
```

And the following configuration:

```
endpoint:
  url: https://myworpresspage.com
  method: GET
  timeout: 1 # seconds
  expectation:
    - type: HTTP_STATUS
      status_range: 200-300
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: ".*WORDPRESS FOOTER HOOK.*"
  allowed_fails: 0
cachet:
  api_url: http://cachet:8000/api/v1
  token: xxxxxxxxxxxxxxxxxxx
  component_id: 1
  metric_id: 1
  action:
    - CREATE_INCIDENT
    - UPDATE_STATUS
  public_incidents: true
frequency: 30
latency_unit: ms
```

It works perfectly, but when cachetHQ sends an email, in the URL inside the email, redirects me to http://cachet:8000/subscribe/manage/xxxxxxx instead of https://myworpresspage.com/subscribe/manage/xxxxxxx in button "manage subscriptions"

I do not understand the API very well, but you could place an API URL and a LINK (A hyperlink to the component)???
