### ISSUE TITLE
Release-0.6.4 doesn't load config file anymore

### ISSUE THREAD

**Issue by chris-str-cst** [mtakaki/cachet-url-monitor#81]
```bash
cachet-monitor_1  | Traceback (most recent call last):
cachet-monitor_1  |   File "./cachet_url_monitor/scheduler.py", line 144, in <module>
cachet-monitor_1  |     token = os.environ.get('CACHET_TOKEN') or config_data['cachet']['token']
cachet-monitor_1  | NameError: name 'os' is not defined
```

```yaml
cachet-monitor:
    # https://github.com/mtakaki/cachet-url-monitor/blob/master/config.yml
    image: mtakaki/cachet-url-monitor:release-0.6.4
    volumes: 
      - "${PWD}/config.yml:/usr/src/app/config/config.yml:ro"
```
It works with release-0.6.3
